server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ZebraAssignment
    username: postgres
    password: asd123asd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
